### ISSUE TITLE
Recomendacion: Cambio de Color

### ISSUE THREAD

**Issue by joe7hann** [Zakuhest/trivia#1]
En las lineas 45 y 49, recomendaría cambiar el color (NEGRO), ya que en consolas con fondo negro, casi no se nota la existencia de este.
```
  for time_carga in range (6,0,-1): #desafio a
    if c in (1,3):
      time.sleep(1)
      print(BLACK+"\n"+mensaje_carga+RESET) #45
      c = 1
      
    time.sleep(1)
    print(BLACK+mensaje_carga+"."*c+RESET) #49
    c += 1
```

**Comment by Zakuhest** [comment]
Se ha actualizado de acuerdo a su recomendación y se ha establecido un color visible para cualquier consola. Esto se puede corroborar en pull request y el código mejorado.
