### ISSUE TITLE
Recomendacion: Cambiar de color

### ISSUE THREAD

**Issue by joe7hann** [Zakuhest/trivia#4]
Se veri'a de mejor manera si, Al momento de ingresar un valor erroneo a las alternativas, cambiar la segunda li'nea a un color (Rojo) ya que significa advertencia para darle ma's e'nfasis a este.
![image](https://user-images.githubusercontent.com/67933223/190840999-0b8d4083-aa3e-4993-b502-1e6b3373ccb5.png)

**Comment by Zakuhest** [comment]
El color del mensaje se ha cambiado a rojo tal cual su recomendación, es una mejora estética pero de suma importancia para el usuario. 
Las mejoras se pueden visualizar en el pull request realizado y el código actualizado.
