### ISSUE TITLE
Bug: Error al momento de mostrar el puntaje actual y final

### ISSUE THREAD

**Issue by joe7hann** [Zakuhest/trivia#5]
No revise' el co'digo en esta parte, sin embargo, al momento de mostrar el puntaje, este no muestra el que deberi'a.
Me dice **Puntaje actual = -1** pero al final me dice que **Alcanzaste 11 puntos**. En caso de haber un **BONUS** de puntaje deberi'a de mostrarse este en la consola tambie'n.
![image](https://user-images.githubusercontent.com/67933223/190841102-2294ba83-4255-45b2-9368-0914b73a8963.png)

**Comment by Zakuhest** [comment]
Se ha realizado la corrección del error, la trivia al final tiene un puntaje bonus por ruleta el cual solo se calculó pero no se mostró. Estan los cambios hechos y puede visualizarse en el pull request hecho junto al codigo actualizado.
