### ISSUE TITLE
Recomendacion: No preguntar Nombre 2 o + veces

### ISSUE THREAD

**Issue by joe7hann** [Zakuhest/trivia#6]
Si al final me pregunta que si **"deseo realizar nuevamente el test"** se supone que es la misma persona, y volver a preguntar el nombre no tiene mucho sentido.
![image](https://user-images.githubusercontent.com/67933223/190841356-a15dc13d-aa6a-4a02-98c9-6f36bfea2674.png)

**Comment by Zakuhest** [comment]
Se ha mejorado y actualizado la trivia de acuerdo a su recomendación. El bucle se ha reposicionado de forma que no se pregunte de nuevo el nombre del jugador y para ello, se guardó el nombre en una lista.
El cambio se puede visualizar por el pull request y el código actualizado.
